name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
        run: cd frontend && npm install
        run: cd backend-ts && npm install
        run: cd cdk-ts && npm install
      - name: Run biome
        run: npx @biomejs/biome check
      - name: Build frontend
        run: cd frontend && npm run build
      - name: Build backend
        run: cd backend-ts && npm run build
      - name: Build CDK
        run: cd cdk-ts && npm run build